version: '{build}'
max_jobs: 1
image: Visual Studio 2019
# History plugin requires complete log
#clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  package_name: p4

install:
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable
  - git --version

build_script:
  - ps: choco pack

test_script:
  - ps: choco install p4 -dvy

notifications:
  - provider: Email
    to: $(mail_user)
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
